name: Deploy App

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to Deploy"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HOST: root@31.43.203.115
      DEPLOY_DIRECTORY: /mnt/disk1/restgrpcproxy
      CONFIG_PATH: /mnt/disk1/restgrpcproxy/config/prod.yaml
      DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Check if tag exists
        run: |
          git fetch --all --tags
          if ! git tag | grep -q "^${{ github.event.inputs.tag }}$"; then
            echo "error: Tag '${{ github.event.inputs.tag }}' not found"
            exit 1
          fi
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.2
      - name: Build app
        run: |
          go mod download
          go build -o restgrpcproxy ./cmd/restgrpcproxy
      - name: Deploy to VM
        run: |
          sudo apt-get install -y ssh rsync
          echo "$DEPLOY_SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "mkdir -p ${{ env.DEPLOY_DIRECTORY }}"
          rsync -avz -e 'ssh -i deploy_key.pem -o StrictHostKeyChecking=no' --exclude='.git' ./ ${{ env.HOST }}:${{ env.DEPLOY_DIRECTORY }}
      - name: Remove old systemd service file
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "rm -f /etc/systemd/system/restgrpcproxy.service"
      - name: List workspace contents
        run: |
          echo "Listing deployment folder contents:"
          ls -la ${{ github.workspace }}/deployment
      - name: Copy systemd service file
        run: |
          scp -i deploy_key.pem -o StrictHostKeyChecking=no ${{ github.workspace }}/deployment/restgrpcproxy.service ${{ env.HOST }}:/tmp/restgrpcproxy.service
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "mv /tmp/restgrpcproxy.service /etc/systemd/system/restgrpcproxy.service"
      - name: Start application
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "systemctl daemon-reload && systemctl restart restgrpcproxy.service"
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "systemctl enable restgrpcproxy"
